Support registry keys in forensicartifacts
yeti-platform/yeti pull request #1028
Opened 2024-02-28 21:11 UTC by tomchop

2024-03-01 06:51 UTC, udgover approved these changes
LGTM!

2024-03-01 14:15 UTC, sebdraven requested changes

2024-03-01 14:15 UTC, sebdraven commented on core/schemas/indicator.py
> +                            relevant_tags=self.relevant_tags,
it's not better to use tag with the new feature on indicators ?

2024-03-02 18:29 UTC, sebdraven approved these changes

2024-03-02 18:34 UTC, merged