Adds CISA KEV feed with NIST NVD details
yeti-platform/yeti pull request #892
Opened 2023-11-16 11:31 UTC by udgover

2023-11-16 11:48 UTC, tomchop requested changes
This looks great, but it's worth revisiting by making some stronger assumptions about the correctness of your dict. (and I think they should be made, otherwise you're gonna have to account for every possible corner-case and that will unnecessarily complexify the code)

2023-11-16 11:48 UTC, tomchop commented on plugins/feeds/public/cisa_kev.py
> +            self.analyze_entry(entry, cve_details)
Here you might be passing `None` as a second arg to analyze_entry, and the function doesn't take that into account. 

Maybe check that `cve_details is not None` before proceeding or just assume that the JSON is well-formed and access the key directly (preferable)

2023-11-16 11:48 UTC, tomchop commented on plugins/feeds/public/cisa_kev.py
> +        cve_id = entry.get('cveID')
You already know that this key exists, so no need to use get. Also, you're using get but not checking for the actual value of `cve_id`

2023-11-16 11:48 UTC, tomchop commented on plugins/feeds/public/cisa_kev.py
> +        description += f"* Product: {entry.get('product')}\n"
if `get` here fails, we're left with `None`. Better add a default return value like "N/A" ?

2023-11-16 11:48 UTC, tomchop commented on plugins/feeds/public/cisa_kev.py
> +            description += f"* **Access Vector (AV):** {cvss_data.get('accessVector').capitalize()}\n"
If the key doesn't exist in the dict (which is presumably why you're using `get`), you'll get an attribute error:

```
>>> {}.get('asd').capitalize()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'capitalize'
```

2023-11-16 14:26 UTC, udgover commented on plugins/feeds/public/cisa_kev.py
> +            self.analyze_entry(entry, cve_details)
Fixed!

2023-11-16 14:26 UTC, udgover commented on plugins/feeds/public/cisa_kev.py
> +        cve_id = entry.get('cveID')
Fixed!

2023-11-16 14:26 UTC, udgover commented on plugins/feeds/public/cisa_kev.py
> +        description += f"* Product: {entry.get('product')}\n"
Fixed!

2023-11-16 14:26 UTC, udgover commented on plugins/feeds/public/cisa_kev.py
> +            description += f"* **Access Vector (AV):** {cvss_data.get('accessVector').capitalize()}\n"
Fixed!

2023-11-16 16:31 UTC, tomchop commented on plugins/feeds/public/cisa_kev.py
> +        cve = cve_details.get('cve')
```suggestion
        cve = cve_details['cve']
```

(or `.get('cve', {})` if it's likely to be missing)

The whole logic under this (e.g. L76) assumes cve is a dict. (

2023-11-16 16:35 UTC, tomchop commented on plugins/feeds/public/cisa_kev.py
> +                continue
```suggestion
            if not entry.get('cveID'):
                continue
```

(This also works if the key is actually set but the value's truthiness is False (`False`, `None`, `[]`, `''`, etc.)

2023-11-16 16:37 UTC, tomchop commented on plugins/feeds/public/cisa_kev.py
> +            self.analyze_entry(entry, cve_details)
```suggestion
            cve_details = nvd_json.get(cve_id, {})
            if not cve_details:
              continue
            self.analyze_entry(entry, cve_details)
```

Should we just skip calling `analyze_entry` if `cve_details` is empty? Given the test in L 67 and 68, it might be clearer do the check here.


Should we just skip calling `analyze_entry` if `cve_details` is empty? Given the test in L 67 and 68, it might be clearer do the check here.

2023-11-16 16:38 UTC, tomchop commented on plugins/feeds/public/cisa_kev.py
> +        if not isinstance(cve_details, dict) or len(cve_details) == 0:
What other type can `cve_details` be if not a dict? 🤔

2023-11-16 16:45 UTC, udgover commented on plugins/feeds/public/cisa_kev.py
> +            self.analyze_entry(entry, cve_details)
That's a good point. cve_details adds context to KEV information. If cve_details do not exist, we still want to have the KEV entry I think. Wdyt?

2023-11-16 16:46 UTC, udgover commented on plugins/feeds/public/cisa_kev.py
> +        if not isinstance(cve_details, dict) or len(cve_details) == 0:
It's only dict :) I was just adding the right test even if this method is not called on its own externally.

2023-11-16 16:49 UTC, udgover commented on plugins/feeds/public/cisa_kev.py
> +        cve = cve_details.get('cve')
I'm more in favor of using .get('cve', {})

2023-11-16 17:03 UTC, tomchop commented on plugins/feeds/public/cisa_kev.py
> +            self.analyze_entry(entry, cve_details)
Yes, agreed!

2023-11-17 12:31 UTC, tomchop approved these changes
LGTM

2023-11-17 13:29 UTC, merged