Wallet improvements
yeti-platform/yeti pull request #982
Opened 2024-01-15 11:20 UTC by udgover

2024-01-15 14:43 UTC, tomchop requested changes

2024-01-15 14:43 UTC, tomchop commented on core/schemas/observables/wallet.py
> +    address: str | None = None
If they *must* be provided, then let's not set them to optional? (`| None`)

2024-01-18 09:52 UTC, tomchop approved these changes
LGTM! but please update the observable fields before merging

2024-01-18 10:54 UTC, merged

2024-02-02 16:44 UTC, sebdraven commented
fixes #940