Support IBAN & BIC observables
yeti-platform/yeti pull request #985
Opened 2024-01-18 23:26 UTC by p-l-

2024-01-19 08:34 UTC, tomchop requested changes
Small nit regarding uppercase, otherwise LGTM!

2024-01-19 08:34 UTC, tomchop commented on core/schemas/observables/iban.py
> +class Iban(observable.Observable):
```suggestion
class IBAN(observable.Observable):
```

We use uppercase for other observables made of acronyms such as CIDR. (granted, some are not compliant with this, we might change it in the future)

2024-01-19 08:34 UTC, tomchop commented on core/schemas/observables/bic.py
> +class Bic(observable.Observable):
```suggestion
class BIC(observable.Observable):
```

2024-01-19 08:36 UTC, tomchop commented
Also worth noting that if you want them to be visible from the UI you'll have to add these to observableDefinitions.json in yeti-feeds-frontend: https://github.com/yeti-platform/yeti-feeds-frontend/blob/main/src/definitions/observableDefinitions.js

2024-01-19 21:29 UTC, p-l- commented
Hey @tomchop!

Thanks for your review! I have updated the PR (could not merge your suggestions directly since it had to be changed everywhere).

> Also worth noting that if you want them to be visible from the UI you'll have to add these to observableDefinitions.json in yeti-feeds-frontend

That's planned yes!

2024-01-20 17:27 UTC, tomchop approved these changes

2024-01-20 17:27 UTC, tomchop commented
Excellent, thanks! Will also have a look at the other one (and merge it)

2024-01-20 17:28 UTC, merged