Add support for running Censys queries via analytics
yeti-platform/yeti pull request #988
Opened 2024-01-23 17:12 UTC by itsmvd

This allows Yeti users to add Censys queries as indicators, which will then be ran through the Censys API every 24 hours, tagging the identified IP addresses in Yeti. This will allow for infrastructure tracking/hunting directly from within Yeti.

2024-01-23 18:48 UTC, itsmvd commented
Related PR for the frontend: https://github.com/yeti-platform/yeti-feeds-frontend/pull/142

2024-01-24 08:23 UTC, tomchop requested changes

2024-01-24 08:23 UTC, tomchop commented on plugins/analytics/public/censys.py
> +  def query_censys(self, api, query: str) -> set[str]:
```suggestion
  def query_censys(self, api: CensysHosts, query: str) -> set[str]:
```

2024-01-24 08:23 UTC, tomchop commented on plugins/analytics/public/censys.py
> +        )
Please check that these two config settings are set and bail with a warning (logging.warning) if they're not?

2024-01-24 08:23 UTC, tomchop commented on plugins/analytics/public/censys.py
Please give it a ruff formatter pass (We'll add a github action check soon)

2024-01-24 08:23 UTC, tomchop commented on tests/analytics_test.py
> +        database_arango.db.connect(database="yeti-test")
```suggestion
        database_arango.db.connect(database="yeti_test")
```

2024-01-24 08:23 UTC, tomchop commented on tests/analytics_test.py
Same comment as the other file, please give this a ruff formatter pass

2024-01-25 13:53 UTC, tomchop approved these changes
LGTM, thanks!!

2024-01-25 13:54 UTC, merged