Import Misp Json format
yeti-platform/yeti pull request #990
Opened 2024-01-24 16:41 UTC by sebdraven

2024-01-25 14:05 UTC, tomchop requested changes

2024-01-25 14:05 UTC, tomchop commented on core/common/misp_to_yeti.py
> +        obs_yeti = links.pop()
Why pop() here? Why is the first item of the loop the one that gets links to everything else?

2024-01-25 14:05 UTC, tomchop commented on core/common/misp_to_yeti.py
> +            obs_yeti.link_to(obj_to_link,f'link_by_misp_{objs_type}','misp')
link_to takes 3 params: the target object, a short description (will show in the link table), and a longer description (will only show on hover; so you can add more context there)

2024-01-25 14:05 UTC, tomchop commented on tests/apiv2/import_data.py
> +                "Galaxy": [],
Let's put all this blob in a file under `tests/misp_test_data/misp.json`

2024-01-25 14:05 UTC, tomchop commented on tests/apiv2/import_data.py
> +
It woudl also be good to assert that the observables that are created are properly formed (right values, right neighbors, etc.)

2024-01-26 10:01 UTC, udgover requested changes
That's a good start but some questions to answer. We should also agree on the formatter / linter to use because lots of changes comes from formatting and review is harder.

Finally, you MUST add the authentication check for the new API endpoint.

2024-01-26 22:03 UTC, sebdraven commented on core/schemas/observable.py
> +                                      ipv4, ipv6, mac_address, md5, path,mutex,named_pipe,
It's just to add for this PR. I'll do that for the next one

2024-02-02 11:23 UTC, sebdraven commented on core/web/apiv2/import_data.py
> +@router.post("/import_misp_json", tags=["import_misp_json"])
nop, after we want to bulk csv, or stix format ;)

2024-02-02 16:49 UTC, tomchop approved these changes

2024-02-02 16:49 UTC, tomchop approved these changes

2024-02-02 19:08 UTC, merged