Add feed which imports domains and ipv4 mining pools from mining pool…
yeti-platform/yeti pull request #995
Opened 2024-01-27 12:51 UTC by udgover

2024-01-27 12:52 UTC, udgover commented
It's related to minerstat feature request but relies on another source. Latest update from Minerstat feed is end of November 2023.

2024-01-29 13:40 UTC, tomchop requested changes

2024-01-29 13:40 UTC, tomchop commented on plugins/feeds/public/miningpoolstats.py
> +        headers = {"User-Agent": self._USER_AGENT}
Consider (re)using a requests Session object across the feed (will multiplex HTTP requests using the same UA and any cookies that are set)

2024-01-29 13:40 UTC, tomchop commented on plugins/feeds/public/miningpoolstats.py
> +    def _get_coin_names(self):
plz add type annotations

2024-02-03 16:03 UTC, tomchop approved these changes
one small nit, otherwise lgtm!

2024-02-03 16:20 UTC, tomchop requested changes

2024-02-03 16:20 UTC, tomchop commented on plugins/feeds/public/miningpoolstats.py
> +                url_obs = None
```suggestion
```

2024-02-03 16:22 UTC, merged